version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: skattehjalpen-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: skattehjalpen
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - skattehjalpen-network

networks:
  skattehjalpen-network:
    driver: bridge

volumes:
  mongodb_data: